### PR TITLE
LPS-73829 Include field for NTLM Negotiate Flags property in Instance Settings

### PR DESCRIPTION
**Pull request by rodrigopaulino**
Relevant ticket:
https://issues.liferay.com/browse/LPS-73829

Note:
I've added a new line in Language.properties but I wasn't able to run the buildLang task in this subrepo because it is not implemented.

### CODE REVIEW

**Comment by topolik** [comment]
Hi @rodrigopaulino,

I'm sorry I didn't get to it. 

@stian-sigvartsen, @csierra can you please look at it? Should be easy to review. Thanks guys!

**Comment by rodrigopaulino** [comment]
Hey, @topolik.
Is there an estimated time for concluding this review?
Thanks.

**Comment by csierra** [comment]
please see https://github.com/brianchandotcom/liferay-portal/pull/51286

**Comment by csierra** [comment]
as I have been told this repositories are not still active so, please, send your pull requests to liferay-portal @rodrigopaulino and close this one.
Thanks.

**Pull request closed without merging**
